### ISSUE TITLE
v2.0.0 gives error when running ember deploy

### ISSUE THREAD

**Issue by akatov** [ember-cli/broccoli-uglify-sourcemap#53]
```
Error: The Broccoli Plugin: [Fingerprint] failed with:
Error: ENOENT: no such file or directory, open '/repo/tmp/uglify_writer-input_base_path-ZtW0omFx.tmp/assets/dag-map.js.map'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at UglifyWriter.processFile (/repo/node_modules/broccoli-uglify-sourcemap/index.js:101:41)
    at /repo/node_modules/broccoli-uglify-sourcemap/index.js:65:16
    at Array.forEach (<anonymous>)
    at /repo/node_modules/broccoli-uglify-sourcemap/index.js:55:25
    at Array.forEach (<anonymous>)
    at UglifyWriter.build (/repo/node_modules/broccoli-uglify-sourcemap/index.js:54:19)
    at /repo/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/repo/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/repo/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/repo/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/repo/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I suspect this is because of the upgrade to `source-map-url: ^0.4.0`

**Comment by akatov** [comment]
I think this is pretty much the same issue as https://github.com/ember-cli/ember-cli-uglify/issues/29

**Comment by urbany** [comment]
I added a comment there I think it's not solved for every case yet: https://github.com/ember-cli/ember-cli-uglify/issues/29#issuecomment-336085319

**Comment by rwjblue** [comment]
@urbany - #29 was not a bug in ember-cli-uglify (but was instead a bug in the actual source files that Ember generated). So far there is no evidence that an actual bug exists in this repo...

**Comment by urbany** [comment]
Thank you for the quick reply Robert!
I'm not sure how all the pieces fit together, but shouldn't the broccoli-uglify-sourcemap remove the `//# sourceMappingURL=popper.js.map` when joining all the vendor files into the vendor.js?since the popper.js.map is already in the cendor.map there is no need to have the `//# sourceMappingURL=popper.js.map` comment right?

**Comment by 0xadada** [comment]
Workaround for this was to disable sourcemaps in production builds

## ember-cli-build.js

```javascript
// ...
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

// ...
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: EmberApp.env() !== 'production',
    },
   // ...
```
